### PR TITLE
Restored vertical metrics.

### LINKED ISSUE #10: Vert metrics have been modified
I previously set the metrics in ec2ce5953c43e3aee519e334bcae0ad916fe1f35. They have now been modified and made much looser.

charm_spacing

cc @davelab6

### PR DESCRIPTION
**Pull request by m4rc1e**
I see you folks have already scaled the fonts since I last made my updates! thank you for doing this.

Fixes #10

### CODE REVIEW

**Comment by m4rc1e** [comment]
In https://github.com/google/fonts/pull/1720 @davelab6 noticed some glyph names were longer than 32 characters.

I've shortened the names of the offending glyphs. However, I didn't change the OT feature input to access these glyphs. This means that users' documents won't be affected.

## Fontbakery report

<details>
<summary><b>[1] Family checks</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Check font has a license.</summary>

* [com.google.fonts/check/028](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/028)
* :fire: **FAIL** No license file was found. Please add an OFL.txt or a LICENSE.txt file. If you are running fontbakery on a Google Fonts upstream repo, which is fine, just make sure there is a temporary license file in the same folder. [code: no-license]

</details>
<br>
</details>
<details>
<summary><b>[2] Charm-Bold.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Font has ttfautohint params? </summary>

* [com.google.fonts/check/has_ttfautohint_params](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/has_ttfautohint_params)
* :fire: **FAIL** Font is lacking ttfautohint params on its version strings on the name table.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Check if OS/2 xAvgCharWidth is correct.</summary>

* [com.google.fonts/check/034](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/034)
* :fire: **FAIL** OS/2 xAvgCharWidth is 518 but it should be 533 which corresponds to the weighted average of the widths of the latin lowercase glyphs in the font

</details>
<br>
</details>
<details>
<summary><b>[2] Charm-Regular.ttf</b></summary>
<details>
<summary>:fire: <b>FAIL:</b> Font has ttfautohint params? </summary>

* [com.google.fonts/check/has_ttfautohint_params](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/has_ttfautohint_params)
* :fire: **FAIL** Font is lacking ttfautohint params on its version strings on the name table.

</details>
<details>
<summary>:fire: <b>FAIL:</b> Check if OS/2 xAvgCharWidth is correct.</summary>

* [com.google.fonts/check/034](https://github.com/googlefonts/fontbakery/search?q=com.google.fonts/check/034)
* :fire: **FAIL** OS/2 xAvgCharWidth is 503 but it should be 517 which corresponds to the weighted average of the widths of the latin lowercase glyphs in the font

</details>
<br>
</details>

### Summary

| :broken_heart: ERROR | :fire: FAIL | :warning: WARN | :zzz: SKIP | :information_source: INFO | :bread: PASS |
|:-----:|:----:|:----:|:----:|:----:|:----:|
| 0 | 5 | 10 | 93 | 14 | 124 |
| 0% | 2% | 4% | 38% | 6% | 50% |

**Note:** The following loglevels were omitted in this report:
* **WARN**
* **SKIP**
* **INFO**
* **PASS**

@davelab6 the fonts are still unhinted. We did this because we wanted to release them as VFs in the future.

**Comment by davelab6** [comment]
Unhinted is good.

**Comment by m4rc1e** [comment]
Once this is merged, we can pr to google/fonts.

If we're desperate, I can update it now.

**Comment by davelab6** [comment]
I'm going ahead and merging this now, as it needs to be done.

**Pull request merged**
